In [1]:
nbits = 4
d = 2

import numpy as np
plane_norms = np.random.rand(nbits, d) - 0.5
plane_norms

array([[ 0.13777669, -0.02495876],
       [ 0.41197829, -0.39384368],
       [ 0.49666627, -0.30594639],
       [ 0.36978375,  0.45590994]])

In [2]:
a = np.asarray([1, 2])
b = np.asarray([2, 1])
c = np.asarray([3, 1])

a_dot = np.dot(a, plane_norms.T)
b_dot = np.dot(b, plane_norms.T)
c_dot = np.dot(c, plane_norms.T)
a_dot

array([ 0.08785916, -0.37570908, -0.11522651,  1.28160362])

In [3]:
a_dot = a_dot > 0
b_dot = b_dot > 0
c_dot = c_dot > 0
a_dot


array([ True, False, False,  True])

In [4]:
a_dot = a_dot.astype(int)
b_dot = b_dot.astype(int)
c_dot = c_dot.astype(int)
a_dot

array([1, 0, 0, 1])

In [5]:
vectors = [a_dot, b_dot, c_dot]
buckets = {}
i = 0

for i in range(len(vectors)):
    has_str = ''.join(vectors[i].astype(str))
    if has_str in buckets:
        buckets[has_str].append(i)
    else:
        buckets[has_str] = [i]
        
print(buckets)

{'1001': [0], '1111': [1, 2]}


In [1]:
import tarfile

# the download leaves us with a tar.gz file, we unzip it
tar = tarfile.open('sift.tar.gz', "r:gz")
tar.extractall()
import numpy as np

# now define a function to read the fvecs file format of Sift1M dataset
def read_fvecs(fp):
    a = np.fromfile(fp, dtype='int32')
    d = a[0]
    return a.reshape(-1, d + 1)[:, 1:].copy().view('float32')

xb = read_fvecs('./sift/sift_base.fvecs')  # 1M samples
# also get some query vectors to search with
xq = read_fvecs('./sift/sift_query.fvecs')
# take just one query (there are many in sift_learn.fvecs)
xq = xq[0].reshape(1, xq.shape[1])

In [2]:
import faiss
d = xb.shape[1]
nbits = 4



In [ ]:
index= faiss.IndexLSH(d, nbits)
index.add(xb)

In [3]:
d

128

In [5]:

M = 32
index = faiss.IndexHNSWFlat(d, M)
print(index.hnsw)

<faiss.swigfaiss.HNSW; proxy of <Swig Object of type 'faiss::HNSW *' at 0x105ba5bf0> >


In [6]:
levels = faiss.vector_to_array(index.hnsw.levels)
np.bincount(levels)

array([], dtype=int64)

In [ ]:
index.add(xb)